### PR TITLE
Add runbook for LowVirtAPICount alert

### PR DESCRIPTION
**Pull request by sradco**
Signed-off-by: Shirly Radco <sradco@redhat.com>

### CODE REVIEW

**Comment by djfjeff** [comment]
To make this runbook compatible with both upstream and downstream, would you consider exporting the namespace and using it after (for example, kubevirt for upstream, openshift-cnv for downstream)? I see in other runbook the following :

- Set the environment variable NAMESPACE

```
export NAMESPACE="$(kubectl get kubevirt -A -o custom-columns="":.metadata.namespace)"
```

- Then use it in other commands, for example

`kubectl -n $NAMESPACE get pods -l kubevirt.io=virt-api`

**Comment by sradco** [comment]
> To make this runbook compatible with both upstream and downstream, would you consider exporting the namespace and using it after (for example, kubevirt for upstream, openshift-cnv for downstream)? I see in other runbook the following :
> 
> * Set the environment variable NAMESPACE
> 
> ```
> export NAMESPACE="$(kubectl get kubevirt -A -o custom-columns="":.metadata.namespace)"
> ```
> 
> * Then use it in other commands, for example
> 
> `kubectl -n $NAMESPACE get pods -l kubevirt.io=virt-api`

@djfjeff Updated

**Comment by djfjeff** [comment]
@sradco this looks good to me!

**Pull request merged**
