### PR TITLE
Add public copyright license

### PR DESCRIPTION
**Pull request by assafad**
**What this PR does**:
Add public copyright license to all files in the repo.

Fixes https://github.com/kubevirt/monitoring/issues/206
Jira-ticket: https://issues.redhat.com/browse/CNV-41504

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by sradco** [comment]
@assafad I think you are missing the LICENSE file.
Like here: https://github.com/kubevirt/containerized-data-importer/blob/main/LICENSE

**Comment by machadovilaca** [comment]
what do you think about adding to the makefile and https://github.com/kubevirt/monitoring/blob/main/.github/workflows/sanity.yaml a check that all new files have a/this copyright header?

**Comment by assafad** [comment]
> what do you think about adding to the makefile and https://github.com/kubevirt/monitoring/blob/main/.github/workflows/sanity.yaml a check that all new files have a/this copyright header?

Do you know any specific tool that we can use? Asking because I don't think we should implement it from scratch in this repo. I found https://github.com/palantir/go-license for example.

**Comment by assafad** [comment]
@machadovilaca Can we merge this PR and have the validation tool discussion later?
1. The current PR changes won't need to be reverted.
2. If we need to write this tool from scratch, IMO we need to implement it elsewhere, since it's not monitoring related, and then we can apply in all kubevirt org repos. Personally I don't think it worth the effort for this particular repo, which has a small group of contributes and reviewers.

**Review by machadovilaca — APPROVED** [review]

**Comment by assafad** [comment]
@sradco can we merge this one?

**Comment by sradco** [comment]
Hi @assafad,  Please mention that it also fixes https://github.com/kubevirt/monitoring/issues/206

**Comment by sradco** [comment]
@assafad I agree with @machadovilaca that we need a test to check that if a new go file is added, then it should have the license text at the top.
If needed, please open a separate story to make sure this is implemented.

**Comment by assafad** [comment]
@sradco Created https://issues.redhat.com/browse/CNV-44881. 
I agree this tool is useful, we are on the same page about this. I just think it shouldn't be in kubevirt/monitoring repo, but we can discuss it before starting to work on that.

**Pull request merged**
