### PR TITLE
Update KubevirtVmHighMemoryUsage Playbook

### PR DESCRIPTION
**Pull request by hoo29**
**What this PR does / why we need it**:

The playbook for KubevirtVmHighMemoryUsage is now out of date with the alert itself.

The threshold for the alert got changed from 20MB to 50MB in https://github.com/kubevirt/kubevirt/pull/9834

The units got updated in the alert description in https://github.com/kubevirt/kubevirt/pull/9073

The alert changed from using pod limits to request in https://github.com/kubevirt/kubevirt/pull/7204

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
Update KubevirtVmHighMemoryUsage playbook wording
```

### CODE REVIEW

**Comment by sradco** [comment]
@hoo29  Thank you for opening this issue.
We plan to deprecate this alert, since its not very useful and we are working to fix this in other ways.
It can be safely silenced.

**Comment by hoo29** [comment]
@sradco - thanks for letting me know. Are there any other alerts you are planning on deprecating that we can ignore?

**Comment by sradco** [comment]
@hoo29 See https://github.com/kubevirt/monitoring/pull/222

**Comment by sradco** [comment]
I'm closing this issue, but feel free to reopen if needed.

**Pull request closed without merging**
